.. This (-*- rst -*-) format file contains commonly used link targets and name
   substitutions.  It may be included in many files, therefore it should only
   contain link targets and name substitutions. Try grepping for "^\.\. _" to
   find plausible candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for:
   nipy, NIPY, Nipy, etc...


.. project

.. _project pypi: https://pypi.org/project/hipsta/
.. _project github: https://github.com/Deep-MI/Hipsta
.. _project license: https://github.com/Deep-MI/Hipsta/blob/master/LICENSE


.. license

.. _MIT license: https://opensource.org/licenses/MIT


.. numpy

.. _numpy: https://numpy.org/


.. sklearn

.. _scikit-learn: https://scikit-learn.org/stable/


.. scipy

.. _scipy: https://scipy.org/
